# Lecture 8--Ensemble Learning

## 1. Programming: Bootstrap

In [25]:
import numpy as np
import pandas as pd
from cleands import *

def generate_mvt_normal(n,r,means=None):
    if means is None: means = np.zeros(size=(r,))
    if r == 1: return np.random.normal(loc=means,size=(n,1))
    P = np.array([[1,1]])
    for i in range(2,r):
        ones = np.ones([i,1])
        zeros = np.zeros([P.shape[0],1])
        ident = np.eye(i)
        upper = np.hstack([ones,ident])
        lower = np.hstack([zeros,P])
        P = np.vstack([upper,lower])
    covariates = np.random.normal(size=(n,P.shape[0]))
    idiosyncratics = np.random.normal(loc=means,size=(n,P.shape[1]))
    covariate_loadings = np.random.uniform(size=P.shape[0])*3-1
    return covariates@np.diagflat(covariate_loadings)@P+idiosyncratics

n = 1000
npx = generate_mvt_normal(n,4,means=np.random.uniform(size=(4,))*2-1)
ones = np.ones((n,1))
onpx = np.hstack((ones,npx))
bvec = np.random.uniform(size=(5,))
npy = np.random.normal(size=(n,))+onpx@bvec

In [27]:
bvec

array([0.57509495, 0.29095844, 0.14446854, 0.28912204, 0.40764241])

In [ ]:
model = least_squares_regressor(onpx,npy)

b = model.params
e = model.residuals


In [33]:
sample = np.random.randint(n,size=(n,))
sambple

array([ 31, 690, 172, 229, 721, 708, 274, 224,  70, 694, 803, 601, 678,
        77, 382, 194, 207, 212, 795, 944, 542, 742, 183, 542, 760, 965,
       335, 971, 441, 837, 163, 105, 255,  82,   2, 107, 811, 678, 516,
       603, 624, 602, 592, 259, 295,  67, 379, 854, 304, 725, 696,  24,
        96, 328, 240,   9, 417, 129,  98, 243, 409, 991, 837, 610, 440,
       644,  72, 738, 711, 408, 416, 280, 785,  88, 791, 985, 866, 168,
       357, 281,  92, 890, 579,  41, 812, 901, 313, 652, 593, 814,  72,
       311, 838, 306, 629, 912, 934, 847,  69, 551, 829, 910, 831, 563,
       971, 324, 958, 838,  64, 429, 604, 340, 333, 760,  46, 789,  31,
       260,  33, 140, 318, 268, 548, 986,  29, 530, 601, 778, 669, 448,
       609, 824, 854, 274,  76, 686, 743,  60, 693,  82, 541, 571,  42,
        98, 174, 856, 986, 680, 333, 450, 329, 674, 850, 454, 209,  68,
       835, 256, 537,  93, 220, 493, 465, 732, 890, 117, 119, 872, 893,
       763, 743, 718, 106, 468,  12,  16,  48,  44, 762, 554, 38

In [ ]:
newy = onpx[sample]@nb+e[sample]
newx = onpx[sample]
model = least_squares_regressor(newx,newy)
model.params


In [26]:
np.corrcoef(npx.T)

array([[1.        , 0.34619265, 0.02329264, 0.4627711 ],
       [0.34619265, 1.        , 0.09181138, 0.07614651],
       [0.02329264, 0.09181138, 1.        , 0.32559585],
       [0.4627711 , 0.07614651, 0.32559585, 1.        ]])

## 2. Data Science


### 2.1 Bagging

Average multiple models fit with bootstrap samples

### 2.1 Random Forest

Average multiple models fit with subsets of the x variables and bootstrap samples

### 2.2 Boosting

Repeatedly fit trees on the residuals

## 3. Programming challenges

## 3.1 Gradient boosting

Create plots for gradient boosting.

## 3.2 Insertion sort

Put together a code to implement the insertion sort algorithm.

## 3.3 Principal components analysis

Write a PCA class. Add an estimator for the number of principal componenets to use.