# 1.  $k$-Means clustering

In [1]:
import numpy as np
import pandas as pd
from cleands import *

In [2]:
x1 = np.random.normal(loc=np.random.uniform(size=(5,))*10-5,size=(500,5))
x2 = np.random.normal(loc=np.random.uniform(size=(5,))*10-5,size=(500,5))
x3 = np.random.normal(loc=np.random.uniform(size=(5,))*10-5,size=(500,5))
x = np.vstack((x1,x2,x3))
shuffle = np.random.permutation(x.shape[0])
x = x[shuffle,:]
membership = shuffle.copy()
for i in range(len(membership)):
    if membership[i]<500: membership[i]=0
    elif membership[i]<1000: membership[i]=1
    else: membership[i]=2
np.unique(membership,return_counts=True)

(array([0, 1, 2]), array([500, 500, 500], dtype=int64))

In [44]:
x.shape[0]

1500

In [ ]:
def kmeans(x,k):
    n  = x.shape[0]
    groups = np.random.randint(k,size=(n,)
    values = np.zeros((k,))
    newvalues = np.unique(groups,return_counts=True)
    while
                            

In [3]:
def kmeans(x,k):
    n = x.shape[0]
    groups = np.random.randint(k,size=(n,))
    values = np.zeros((k,))
    newvalues = np.unique(groups,return_counts=True)[1]
    while (newvalues!=values).any() if isinstance(newvalues!=values,np.ndarray) else False:
        values = newvalues
        means = []
        dists = []
        for i in range(k):
            mean = x[groups==i,:].mean(0)
            means += [mean]
            dist = x-np.ones((n,1))@mean.reshape(1,-1)
            dist = (dist**2).sum(1)
            dists += [dist]
        groups = np.array(dists).argmin(0)
        newvalues = np.unique(groups,return_counts=True)[1]
    return groups
def rep_kmeans(x,k,n_start=100):
    n = x.shape[0]
    groups = []
    wsses = []
    for i in range(n_start):
        group = kmeans(x,k)
        means = np.array([x[group==i].mean(0) for i in range(np.unique(group).max()+1)])
        wss = sum([((x[group==i]-means[i,:])**2).sum() for i in range(np.unique(group).max()+1)])
        groups += [group]
        wsses += [wss]
    valu = np.array(wsses).argmin()
    return groups[valu]
groups = rep_kmeans(x,3)
means = np.array([x[groups==i].mean(0) for i in range(np.unique(groups).max()+1)])
wss = sum([((x[groups==i]-means[i,:])**2).sum() for i in range(np.unique(groups).max()+1)])
np.unique(groups,return_counts=True)
wss

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  
c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:25: RuntimeWarning: Mean of empty slice.
c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\numpy\core\_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)


7335.550895256064

In [4]:
[((x[groups==i]-means[i,:])**2).sum() for i in np.unique(groups)]

[2513.913168099951, 2405.7354731342866, 2415.9022540218266]

In [5]:
(groups==membership).mean()

0.988

In [6]:
np.hstack((groups.reshape(-1,1),membership.reshape(-1,1)))

array([[1, 1],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [1, 1],
       [1, 1]], dtype=int64)

In [7]:
dummy = lambda x: pd.get_dummies(x).values

In [8]:
dummy(groups).T@dummy(membership)

array([[244,   0,   0],
       [  0, 233,   7],
       [  0,  11, 237]], dtype=uint8)

In [9]:
cmat = dummy(groups).T@dummy(membership)
(cmat.max(0)/cmat.sum(0)).mean()

0.9754098360655737

In [10]:
dummy(groups).sum(1).sum()

1500

# 3. Programming challenges

## 3.1 Quick sort

## 3.2 $k$-Means class structure
