In [1]:
import pandas as pd
import numpy as np

In [2]:
stu_df=pd.read_csv('student-mat.csv')

In [3]:
stu_df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6   
1    ...      yes       no       5         3      3    1    1      3        4   
2    ...      yes       no       4         3      2    2    3      3       10   
3    ...      yes      yes       3         2      2    1    1      5        2   
4    ...       no       no       4         3      2    1    2      5        4   
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...   
390  ...       no       no       5         5      4    4    5      4       11   
391  ...      yes       no       2         4      5    3    4      2        3   
392  ...       no       no       5         5      3    3    3      3        3   
393  ...      yes       no       4         4      1    3    4      5        0   
394  ...      yes       no       3         2      3    3    3      5        5   

    grade  
0       F  
1       F  
2       C  
3       B  
4       C  
..    ...  
390     C  
391     A  
392     C  
393     C  
394     C  

[395 rows x 31 columns]

In [4]:
stu_df['school']

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [5]:
#school
stu_df["school"]= np.where(stu_df["school"]=="GP", 1, 0)

In [6]:
stu_df["school"]

0      1
1      1
2      1
3      1
4      1
      ..
390    0
391    0
392    0
393    0
394    0
Name: school, Length: 395, dtype: int32

In [7]:
#sex
stu_df['sex']=np.where(stu_df['sex']=='F',1,0)

In [8]:
stu_df

school  sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0         1    1   18       U     GT3       A     4     4   at_home   teacher   
1         1    1   17       U     GT3       T     1     1   at_home     other   
2         1    1   15       U     LE3       T     1     1   at_home     other   
3         1    1   15       U     GT3       T     4     2    health  services   
4         1    1   16       U     GT3       T     3     3     other     other   
..      ...  ...  ...     ...     ...     ...   ...   ...       ...       ...   
390       0    0   20       U     LE3       A     2     2  services  services   
391       0    0   17       U     LE3       T     3     1  services  services   
392       0    0   21       R     GT3       T     1     1     other     other   
393       0    0   18       R     LE3       T     3     2  services     other   
394       0    0   19       U     LE3       T     1     1     other   at_home   

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6   
1    ...      yes       no       5         3      3    1    1      3        4   
2    ...      yes       no       4         3      2    2    3      3       10   
3    ...      yes      yes       3         2      2    1    1      5        2   
4    ...       no       no       4         3      2    1    2      5        4   
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...   
390  ...       no       no       5         5      4    4    5      4       11   
391  ...      yes       no       2         4      5    3    4      2        3   
392  ...       no       no       5         5      3    3    3      3        3   
393  ...      yes       no       4         4      1    3    4      5        0   
394  ...      yes       no       3         2      3    3    3      5        5   

    grade  
0       F  
1       F  
2       C  
3       B  
4       C  
..    ...  
390     C  
391     A  
392     C  
393     C  
394     C  

[395 rows x 31 columns]

In [9]:
stu_df['address'].value_counts()

U    307
R     88
Name: address, dtype: int64

In [10]:
stu_df['address']=np.where(stu_df['address']=='U',1,0)

In [11]:
stu_df['address']

0      1
1      1
2      1
3      1
4      1
      ..
390    1
391    1
392    0
393    0
394    1
Name: address, Length: 395, dtype: int32

In [12]:
#famsize
stu_df['famsize'].value_counts()

GT3    281
LE3    114
Name: famsize, dtype: int64

In [13]:
stu_df['famsize']=np.where(stu_df['famsize']=='GT3',1,0)

In [14]:
#pstatus
stu_df['Pstatus'].value_counts()


T    354
A     41
Name: Pstatus, dtype: int64

In [15]:
stu_df['Pstatus']=np.where(stu_df['Pstatus']=='T',1,0)

In [16]:
stu_df['Mjob']

0       at_home
1       at_home
2       at_home
3        health
4         other
         ...   
390    services
391    services
392       other
393    services
394       other
Name: Mjob, Length: 395, dtype: object

In [17]:
#Mjob
stu_df=pd.get_dummies(stu_df, columns=["Mjob"], prefix=["Mjob"])

In [18]:
#Fjob
stu_df=pd.get_dummies(stu_df, columns=["Fjob"], prefix=["Fjob"])

In [19]:
stu_df

school  sex  age  address  famsize  Pstatus  Medu  Fedu  reason guardian  \
0         1    1   18        1        1        0     4     4  course   mother   
1         1    1   17        1        1        1     1     1  course   father   
2         1    1   15        1        0        1     1     1   other   mother   
3         1    1   15        1        1        1     4     2    home   mother   
4         1    1   16        1        1        1     3     3    home   father   
..      ...  ...  ...      ...      ...      ...   ...   ...     ...      ...   
390       0    0   20        1        0        0     2     2  course    other   
391       0    0   17        1        0        1     3     1  course   mother   
392       0    0   21        0        1        1     1     1  course    other   
393       0    0   18        0        0        1     3     2  course   mother   
394       0    0   19        1        0        1     1     1  course   father   

     ...  Mjob_at_home  Mjob_health  Mjob_other Mjob_services Mjob_teacher  \
0    ...             1            0           0             0            0   
1    ...             1            0           0             0            0   
2    ...             1            0           0             0            0   
3    ...             0            1           0             0            0   
4    ...             0            0           1             0            0   
..   ...           ...          ...         ...           ...          ...   
390  ...             0            0           0             1            0   
391  ...             0            0           0             1            0   
392  ...             0            0           1             0            0   
393  ...             0            0           0             1            0   
394  ...             0            0           1             0            0   

    Fjob_at_home Fjob_health Fjob_other Fjob_services Fjob_teacher  
0              0           0          0             0            1  
1              0           0          1             0            0  
2              0           0          1             0            0  
3              0           0          0             1            0  
4              0           0          1             0            0  
..           ...         ...        ...           ...          ...  
390            0           0          0             1            0  
391            0           0          0             1            0  
392            0           0          1             0            0  
393            0           0          1             0            0  
394            1           0          0             0            0  

[395 rows x 39 columns]

In [20]:
#reason

stu_df=pd.get_dummies(stu_df, columns=["reason"], prefix=["reason"])

In [21]:
stu_df.shape


(395, 42)

In [22]:
#guardian
stu_df=pd.get_dummies(stu_df, columns=["guardian"], prefix=["guardian"])

In [23]:
stu_df.shape

(395, 44)

In [24]:
#schoolup
stu_df['schoolsup'].value_counts()

no     344
yes     51
Name: schoolsup, dtype: int64

In [25]:
stu_df['schoolsup']=np.where(stu_df['schoolsup']=='no',1,0)

In [26]:
#famsize
stu_df['famsup'].value_counts()

yes    242
no     153
Name: famsup, dtype: int64

In [27]:
stu_df['famsup']=np.where(stu_df['famsup']=='no',1,0)

In [28]:
#paid
stu_df['paid'].value_counts()

no     214
yes    181
Name: paid, dtype: int64

In [29]:
stu_df['paid']=np.where(stu_df['paid']=='no',1,0)

In [30]:
#activities
stu_df['activities'].value_counts()

yes    201
no     194
Name: activities, dtype: int64

In [31]:
stu_df['activities']=np.where(stu_df['activities']=='no',1,0)

In [32]:
#nursery

stu_df['nursery']=np.where(stu_df['nursery']=='yes',1,0)

In [33]:
#higher
stu_df['higher']=np.where(stu_df['higher']=='yes',1,0)

In [34]:
#internet
stu_df['internet']=np.where(stu_df['internet']=='yes',1,0)

In [35]:
#romantic
stu_df['romantic']=np.where(stu_df['romantic']=='no',1,0)

In [36]:
stu_df.columns



Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid',
       'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'grade',
       'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services',
       'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other',
       'Fjob_services', 'Fjob_teacher', 'reason_course', 'reason_home',
       'reason_other', 'reason_reputation', 'guardian_father',
       'guardian_mother', 'guardian_other'],
      dtype='object')

In [37]:
df1 = stu_df.pop('grade')

In [38]:
df1

0      F
1      F
2      C
3      B
4      C
      ..
390    C
391    A
392    C
393    C
394    C
Name: grade, Length: 395, dtype: object

In [66]:
stu_df

school  sex  age  address  famsize  Pstatus  Medu  Fedu  traveltime  \
0         1    1   18        1        1        0     4     4           2   
1         1    1   17        1        1        1     1     1           1   
2         1    1   15        1        0        1     1     1           1   
3         1    1   15        1        1        1     4     2           1   
4         1    1   16        1        1        1     3     3           1   
..      ...  ...  ...      ...      ...      ...   ...   ...         ...   
390       0    0   20        1        0        0     2     2           1   
391       0    0   17        1        0        1     3     1           2   
392       0    0   21        0        1        1     1     1           1   
393       0    0   18        0        0        1     3     2           3   
394       0    0   19        1        0        1     1     1           1   

     studytime  ...  Fjob_services  Fjob_teacher  reason_course  reason_home  \
0            2  ...              0             1              1            0   
1            2  ...              0             0              1            0   
2            2  ...              0             0              0            0   
3            3  ...              1             0              0            1   
4            2  ...              0             0              0            1   
..         ...  ...            ...           ...            ...          ...   
390          2  ...              1             0              1            0   
391          1  ...              1             0              1            0   
392          1  ...              0             0              1            0   
393          1  ...              0             0              1            0   
394          1  ...              0             0              1            0   

     reason_other  reason_reputation  guardian_father  guardian_mother  \
0               0                  0                0                1   
1               0                  0                1                0   
2               1                  0                0                1   
3               0                  0                0                1   
4               0                  0                1                0   
..            ...                ...              ...              ...   
390             0                  0                0                0   
391             0                  0                0                1   
392             0                  0                0                0   
393             0                  0                0                1   
394             0                  0                1                0   

     guardian_other  grade  
0                 0      F  
1                 0      F  
2                 0      C  
3                 0      B  
4                 0      C  
..              ...    ...  
390               1      C  
391               0      A  
392               1      C  
393               0      C  
394               0      C  

[395 rows x 44 columns]

In [39]:
stu_df['grade']=df1 

In [40]:
stu_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid',
       'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences',
       'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services',
       'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other',
       'Fjob_services', 'Fjob_teacher', 'reason_course', 'reason_home',
       'reason_other', 'reason_reputation', 'guardian_father',
       'guardian_mother', 'guardian_other', 'grade'],
      dtype='object')

In [41]:
X = stu_df.iloc[:,:-1]
y = stu_df.iloc[:,-1]

In [68]:
X

school  sex  age  address  famsize  Pstatus  Medu  Fedu  traveltime  \
0         1    1   18        1        1        0     4     4           2   
1         1    1   17        1        1        1     1     1           1   
2         1    1   15        1        0        1     1     1           1   
3         1    1   15        1        1        1     4     2           1   
4         1    1   16        1        1        1     3     3           1   
..      ...  ...  ...      ...      ...      ...   ...   ...         ...   
390       0    0   20        1        0        0     2     2           1   
391       0    0   17        1        0        1     3     1           2   
392       0    0   21        0        1        1     1     1           1   
393       0    0   18        0        0        1     3     2           3   
394       0    0   19        1        0        1     1     1           1   

     studytime  ...  Fjob_other  Fjob_services  Fjob_teacher  reason_course  \
0            2  ...           0              0             1              1   
1            2  ...           1              0             0              1   
2            2  ...           1              0             0              0   
3            3  ...           0              1             0              0   
4            2  ...           1              0             0              0   
..         ...  ...         ...            ...           ...            ...   
390          2  ...           0              1             0              1   
391          1  ...           0              1             0              1   
392          1  ...           1              0             0              1   
393          1  ...           1              0             0              1   
394          1  ...           0              0             0              1   

     reason_home  reason_other  reason_reputation  guardian_father  \
0              0             0                  0                0   
1              0             0                  0                1   
2              0             1                  0                0   
3              1             0                  0                0   
4              1             0                  0                1   
..           ...           ...                ...              ...   
390            0             0                  0                0   
391            0             0                  0                0   
392            0             0                  0                0   
393            0             0                  0                0   
394            0             0                  0                1   

     guardian_mother  guardian_other  
0                  1               0  
1                  0               0  
2                  1               0  
3                  1               0  
4                  0               0  
..               ...             ...  
390                0               1  
391                1               0  
392                0               1  
393                1               0  
394                0               0  

[395 rows x 43 columns]

In [42]:
X.shape

(395, 43)

In [43]:
y.shape

(395,)

In [44]:
y

0      F
1      F
2      C
3      B
4      C
      ..
390    C
391    A
392    C
393    C
394    C
Name: grade, Length: 395, dtype: object

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

X_train_org,X_test_org,Y_train_org,Y_test_org = train_test_split(X,y,random_state=0,test_size=0.25)

In [46]:
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train_org)
X_test=scaler.transform(X_test_org)

In [47]:
X_train

array([[1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.42857143, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.57142857, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [1.        , 0.        , 0.14285714, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.14285714, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.        , 0.28571429, ..., 0.        , 1.        ,
        0.        ]])

In [48]:
X_test

array([[1.        , 1.        , 0.28571429, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.28571429, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.42857143, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.14285714, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.28571429, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.57142857, ..., 0.        , 0.        ,
        1.        ]])

In [49]:
X_test_data = pd.DataFrame(X_test,index=None)

In [69]:
X_test_data

0    1         2    3    4    5     6         7         8         9   \
0   1.0  1.0  0.285714  1.0  1.0  1.0  1.00  1.000000  0.333333  0.666667   
1   1.0  1.0  0.285714  0.0  1.0  1.0  0.75  1.000000  0.000000  0.666667   
2   1.0  1.0  0.428571  1.0  1.0  1.0  1.00  0.666667  0.000000  0.666667   
3   1.0  1.0  0.142857  1.0  0.0  1.0  1.00  0.666667  0.666667  0.333333   
4   1.0  1.0  0.142857  1.0  1.0  1.0  1.00  0.333333  0.000000  0.333333   
..  ...  ...       ...  ...  ...  ...   ...       ...       ...       ...   
94  1.0  0.0  0.428571  1.0  1.0  1.0  0.50  0.333333  0.000000  0.333333   
95  1.0  1.0  0.142857  1.0  1.0  1.0  1.00  0.666667  0.000000  0.666667   
96  1.0  0.0  0.142857  1.0  1.0  1.0  0.50  0.000000  0.666667  0.000000   
97  1.0  1.0  0.285714  1.0  1.0  1.0  1.00  1.000000  0.000000  0.000000   
98  1.0  1.0  0.571429  1.0  1.0  1.0  0.50  0.000000  0.666667  0.333333   

    ...   33   34   35   36   37   38   39   40   41   42  
0   ...  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
1   ...  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  
2   ...  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
3   ...  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
4   ...  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
94  ...  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  
95  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
96  ...  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
97  ...  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
98  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  

[99 rows x 43 columns]

In [50]:
X_test_data[2].mean()

0.24675324675324664

In [70]:
from sklearn.linear_model import LogisticRegression
softmax_reg = LogisticRegression(multi_class="auto",solver="lbfgs",max_iter=1000,random_state=0)
softmax_reg.fit(X_train, Y_train_org.values.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
print("Train Accuracy",softmax_reg.score(X_train,Y_train_org))
print("Test Accuracy",softmax_reg.score(X_test,Y_test_org))

Train Accuracy 0.5912162162162162
Test Accuracy 0.3434343434343434


In [53]:
y_log = pd.Series([])

In [72]:
y.shape

(395,)

In [55]:
for i in range(len(y)):
    if(y[i]=='A' or y[i]=="B" or y[i]=='C'):
        y_log[i]="Pass"
    else:
        y_log[i]="Fail"    

In [56]:
X_train_log,X_test_log,Y_train_log,Y_test_log=train_test_split(X,y_log,random_state=0,test_size=0.25)

In [57]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_s=scaler.fit_transform(X_train_log)
X_test_s=scaler.transform(X_test_log)

In [58]:
from sklearn.linear_model import LogisticRegression
logistic= LogisticRegression(solver='lbfgs',multi_class='auto',max_iter=1000,random_state=0)

In [59]:
logistic.fit(X_train_s,Y_train_log)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [60]:
print("train accuracy after pass fail conversion",logistic.score(X_train_s,Y_train_log))
print("test accuracy after pass fail conversion",logistic.score(X_test_s,Y_test_log))

train accuracy after pass fail conversion 0.8412162162162162
test accuracy after pass fail conversion 0.8383838383838383


In [61]:
#SVM
from sklearn.svm import SVC

sv= SVC(random_state=0,kernel='rbf',gamma=0.1,C=1)
sv.fit(X_train,Y_train_org)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [62]:
Y_test_org

329    B
318    C
317    C
65     A
59     A
      ..
239    F
63     C
245    A
154    C
311    B
Name: grade, Length: 99, dtype: object

In [63]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred = sv.predict(X_test)
print(confusion_matrix(Y_test_org,y_pred))

[[ 0  2 13  0]
 [ 0  4 20  0]
 [ 1  5 37  0]
 [ 0  0 17  0]]


In [64]:
X_test

array([[1.        , 1.        , 0.28571429, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.28571429, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.42857143, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.14285714, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.28571429, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.57142857, ..., 0.        , 0.        ,
        1.        ]])